spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3307/printmomentum}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:printmomentum}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:printmomentum}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
